//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceFile", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time adjustment request Approved.
        /// </summary>
        internal static string AdjustmentApproved {
            get {
                return ResourceManager.GetString("AdjustmentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time adjustment request Rejected.
        /// </summary>
        internal static string AdjustmentRejected {
            get {
                return ResourceManager.GetString("AdjustmentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a Time Adjustment request.
        /// </summary>
        internal static string AdjustmentRequest {
            get {
                return ResourceManager.GetString("AdjustmentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time adjustment request sent successfully.
        /// </summary>
        internal static string AdjustmentRequestSent {
            get {
                return ResourceManager.GetString("AdjustmentRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href= &apos;AdminTeacherAttendanceAjustment.aspx?id=[ID]&amp;mld=[MID]&amp;emp=[EMP]&apos; &gt;Approve/Reject&lt;/a&gt;.
        /// </summary>
        internal static string AdminAbsentRequestLink {
            get {
                return ResourceManager.GetString("AdminAbsentRequestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[ATTENDENCE]&lt;/span&gt;.
        /// </summary>
        internal static string AttendeceSpan {
            get {
                return ResourceManager.GetString("AttendeceSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td&gt;&lt;span class=&quot;label label-[FLAG]&quot;&gt;[STATUS]&lt;/span&gt;[MESSAGE]&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string AttendenceLogMessage {
            get {
                return ResourceManager.GetString("AttendenceLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry an error occured please try again!.
        /// </summary>
        internal static string Error_msg {
            get {
                return ResourceManager.GetString("Error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[Message]&lt;/span&gt;.
        /// </summary>
        internal static string GeneralStatus {
            get {
                return ResourceManager.GetString("GeneralStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday added successfully.
        /// </summary>
        internal static string HolidaySaved {
            get {
                return ResourceManager.GetString("HolidaySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday updated successfully.
        /// </summary>
        internal static string HolidayUpdated {
            get {
                return ResourceManager.GetString("HolidayUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string InActiveStatus {
            get {
                return ResourceManager.GetString("InActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new Leave Request from [EMPLOYEE_NAME]..
        /// </summary>
        internal static string LeaveRequestReceived {
            get {
                return ResourceManager.GetString("LeaveRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully.
        /// </summary>
        internal static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been saved successfully.
        /// </summary>
        internal static string RecordSaved {
            get {
                return ResourceManager.GetString("RecordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully.
        /// </summary>
        internal static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section updated successfully.
        /// </summary>
        internal static string SectionUpdatedMsg {
            get {
                return ResourceManager.GetString("SectionUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href= &apos;EmployeeAttendanceAjustment.aspx?Id=[ID]&apos; &gt;Send Leave Request&lt;/a&gt;.
        /// </summary>
        internal static string SendAbsentRequestLink {
            get {
                return ResourceManager.GetString("SendAbsentRequestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href= &apos;EmployeeAttendanceAjustment.aspx?Id=[ID]&apos; &gt;Send Request&lt;/a&gt;.
        /// </summary>
        internal static string SendRequestLink {
            get {
                return ResourceManager.GetString("SendRequestLink", resourceCulture);
            }
        }
    }
}
