//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Utility.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?b=[]&quot; class=&quot;active&quot;&gt;All&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=a&amp;b=[]&quot;&gt;a&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=b&amp;b=[]&quot;&gt;b&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=c&amp;b=[]&quot;&gt;c&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=d&amp;b=[]&quot;&gt;d&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=e&amp;b=[]&quot;&gt;e&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=f&amp;b=[]&quot;&gt;f&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmployeeData {
            get {
                return ResourceManager.GetString("EmployeeData", resourceCulture);
            }
        }
    }
}
