//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Utility.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href= &apos;AdminTeacherAttendanceAjustment.aspx?id=[ID]&amp;mld=[MID]&amp;emp=[EMP]&apos;  Target=&apos;&apos;_blank&gt;[Message]&lt;/a&gt;.
        /// </summary>
        public static string AdminAbsentRequestLink {
            get {
                return ResourceManager.GetString("AdminAbsentRequestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asasa.
        /// </summary>
        public static string asasas {
            get {
                return ResourceManager.GetString("asasas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[ATTENDENCE]&lt;/span&gt;.
        /// </summary>
        public static string AttendeceSpan {
            get {
                return ResourceManager.GetString("AttendeceSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td&gt;&lt;span class=&quot;label label-[FLAG]&quot;&gt;[STATUS]&lt;/span&gt;[MESSAGE]&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string AttendenceLogMessage {
            get {
                return ResourceManager.GetString("AttendenceLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[status]&lt;/span&gt;.
        /// </summary>
        public static string ClassVideoForAdmin {
            get {
                return ResourceManager.GetString("ClassVideoForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;msg-time-chat&quot;&gt;
        ///                                      &lt;a class=&quot;message-img&quot; href=&quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;img/chat-avatar.jpg&quot; class=&quot;avatar&quot;&gt;&lt;/a&gt;
        ///                                      &lt;div class=&quot;message-body msg-in&quot;&gt;
        ///                                          &lt;span class=&quot;arrow&quot;&gt;&lt;/span&gt;
        ///                                          &lt;div class=&quot;text&quot;&gt;
        ///                                              &lt;p class=&quot;attribution&quot;&gt;&lt;a href=&quot;#&quot;&gt;[NAME]&lt;/a&gt; at 1:55pm, 13th April 2013&lt;/p&gt;
        ///                         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConversationTemplat {
            get {
                return ResourceManager.GetString("ConversationTemplat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?b=[]&quot; class=&quot;active&quot;&gt;All&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=a&amp;b=[]&quot;&gt;a&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=b&amp;b=[]&quot;&gt;b&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=c&amp;b=[]&quot;&gt;c&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=d&amp;b=[]&quot;&gt;d&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=e&amp;b=[]&quot;&gt;e&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;EmployeeDirectory.aspx?search=f&amp;b=[]&quot;&gt;f&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmployeeCharacter {
            get {
                return ResourceManager.GetString("EmployeeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occur, please contact to the administrator..
        /// </summary>
        public static string Error_Msg {
            get {
                return ResourceManager.GetString("Error_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[expstatus]&lt;/span&gt;.
        /// </summary>
        public static string ExpenseSpan {
            get {
                return ResourceManager.GetString("ExpenseSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[Message]&lt;/span&gt;.
        /// </summary>
        public static string GeneralStatus {
            get {
                return ResourceManager.GetString("GeneralStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href= &apos;EmployeeAttendanceAjustment.aspx?Id=[ID]&apos; &gt;[Message]&lt;/a&gt;.
        /// </summary>
        public static string SendAbsentRequestLink {
            get {
                return ResourceManager.GetString("SendAbsentRequestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href= &apos;EmployeeAttendanceAjustment.aspx?Id=[ID]&apos; &gt;Send Request&lt;/a&gt;.
        /// </summary>
        public static string SendRequestLink {
            get {
                return ResourceManager.GetString("SendRequestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[status]&lt;/span&gt;.
        /// </summary>
        public static string SMSStatus {
            get {
                return ResourceManager.GetString("SMSStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[status]&lt;/span&gt;.
        /// </summary>
        public static string StatusSpan {
            get {
                return ResourceManager.GetString("StatusSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-[STATUS] label-mini&quot;&gt;[status]&lt;/span&gt;.
        /// </summary>
        public static string WorkingDaySpan {
            get {
                return ResourceManager.GetString("WorkingDaySpan", resourceCulture);
            }
        }
    }
}
